// <auto-generated />
using System;
using HorariosPro.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HorariosPro.Api.Migrations
{
    [DbContext(typeof(HorariosProDbContext))]
    partial class HorariosProDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HorariosPro.Api.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("HorariosPro.Api.Models.Seccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("CursoId");

                    b.Property<string>("Profesor")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Sede")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Secciones");
                });

            modelBuilder.Entity("HorariosPro.Api.Models.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<TimeSpan>("HoraFin");

                    b.Property<TimeSpan>("HoraInicio");

                    b.Property<int>("SeccionId");

                    b.HasKey("Id");

                    b.HasIndex("SeccionId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("HorariosPro.Api.Models.Seccion", b =>
                {
                    b.HasOne("HorariosPro.Api.Models.Curso", "Curso")
                        .WithMany("Secciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("HorariosPro.Api.Models.Sesion", b =>
                {
                    b.HasOne("HorariosPro.Api.Models.Seccion", "Seccion")
                        .WithMany("Sesiones")
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("HorariosPro.Api.Models.Curso", b =>
                {
                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("HorariosPro.Api.Models.Seccion", b =>
                {
                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
